spring:
  application:
    name: viewith-server
  profiles:
    include: private

  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/viewith-db
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: debug
    feign: debug

kakao:
  oauth:
    uri: https://kauth.kakao.com
  api:
    uri: https://kapi.kakao.com

security:
  exclude-uris:
    - /
    - /v1
    - /v1/members/login/KAKAO
    - /v1/members/login/APPLE
    - /v1/members/test3
    - /v1/members/test4