spring:
  application:
    name: viewith-server
  profiles:
    include: private
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 10MB         # 단일 파일 한도
      max-request-size: 40MB      # 요청 전체 한도 (파일 여러 개 포함 시)
      enabled: true

  task:
    scheduling:
      time-zone: Asia/Seoul

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: debug
    feign: debug

kakao:
  oauth:
    uri: https://kauth.kakao.com
  api:
    uri: https://kapi.kakao.com

apple:
  oauth:
    uri: https://appleid.apple.com

kopis:
  api:
    uri: https://www.kopis.or.kr/openApi/restful/pblprfr

security:
  exclude-uris:
    - /
    - /health
    - /v1
    - /v1/members/login/**
    - /v1/members/refresh
    - /v1/reviews/list
    - /v1/help/**
    - /v1/performances/search
    - /v1/venues
    - /v1/venues/*
    - /v1/venues/*/filter
    - /v1/venues/*/seats
    - /admin/**
    - /.well-known/acme-challenge/**