spring:
  application:
    name: viewith-server

  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/viewith-db
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace